#####################################################################
## Configuration File for BrowserStartupLauncher (ver1.0)
#####################################################################

[TARGETS]
*
